name: flutter

on:
  push:
    branches: [main]
    paths:
      - "flutter/**"
      - ".github/workflows/flutter.yml"
  pull_request:
    paths:
      - "flutter/**"
      - ".github/workflows/flutter.yml"

jobs:
  build:
    name: Dart SDK
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: flutter
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - run: dart pub get
      - run: dart analyze
      - run: dart test
      - run: dart pub publish --dry-run
